[INTERFACE]
#Set to valid path if dedicated log file is needed 
log_file = None
log_level = ERROR
languages = LAT,ENG,RUS
default_language_index = 0
# Folder for images & sounds
assets_loader = assets
bg_image = white_background.png
font = DejaVu Sans Mono,50
button_debounce_time_ms = 1000
# Time in milliseconds to activate default button after last press
button_reset_to_default_time_ms = 25000
#Settings for button screen size
screen_height = 800
screen_width = 480
#Settings for button frame size
button_frame_height = 650
button_frame_width = 400
button_frame_posXY = 40,75
#Settings for display brightness 0 - 255
screen_brightness_active = 250
screen_brightness_normal = 100
screen_brightness_inactive = 0
working_hours = 7:30,19:00
screen_brightness_path = /sys/class/backlight
#Week days, 0 - Monday, 6 - Sunday
working_days = 0,1,2,3,4
#working_days = 5,6
#Setting screen brightness to min in case of inactivity in minutes
#screen_brightness_to_min = 5
screen_dpms_timeout_secs = 15

#Settings for animated icon
animated_icon_height = 290
animated_icon_width = 290
animated_icon_delay = 40
animated_icon_sys = loading.gif
animated_icon_prn = printer.gif
animated_icon_bc = barcode.gif
animated_icon_ok = verified.gif
animated_icon_not_ok = alarm.gif
animated_icon_no_data = report_not_ready.gif
animated_icon_in_progress = work-in-progress.gif
animated_icon_net = wifi.gif
text_label_font = DejaVu Sans Mono
text_label_font_size = 20
#popup display time ms
popup_display_time = 10000

[BARCODE]
# Accept next barcode after
bc_reader_bounce = 3
bc_reader_boudrate = 9600
bc_reader_port = /dev/ttyACM0
#Barcode reader timeout in secs
bc_timeout=.5
#Regex to validate barcode
bc_regex = ^\d{7,9}#\d{4,5}

[REPORT]
host = 10.100.50.104
#HTTP request connection timeout
httpreq_timeout = 10
#Seconds to wait for report printout (max 10 if watchdog!!!)
report_delay=9
#url template for CURL request
url=http://{}/csp/sarmite/ea.kiosk.pdf.cls?HASH={}&LANG={}
#url for testing host response 
url_test=http://10.100.50.102/csp/sarmite/ea.up.cls
#Printers make and PPD for auto selection, seperated by comma in dict {'HP':'HP_PPD','Canon':Canon_PPD'}
printers="HP": "HP LaserJet Series PCL 6 CUPS","Kyocera": "ECOSYS P3260dn, driverless, cups-filters 1.28.17"
#CUPS schemes to look for printers (not used with latest CUPS verions)
include_schemes = usb,driverless
#Button to activate printer reset at startup
button_printer_reset=1
report_not_ready_msg = Testēšana\nav pabeigta,Testing is\not compleated,Тестирование\не завершено
report_num_pages = Lapu skaits,Number of pages,Количество страниц
[WATCHDOG]
#Watchdog device, Comment to disable
watchdog_device=/dev/watchdog
